export const GET_CONSULTANT_SLOT_LIST_PENDING = 'GET_CONSULTANT_SLOT_LIST_PENDING'
export const GET_CONSULTANT_SLOT_LIST_FULFILLED = 'GET_CONSULTANT_SLOT_LIST_FULFILLED'
export const GET_CONSULTANT_SLOT_LIST_REJECTED = 'GET_CONSULTANT_SLOT_LIST_REJECTED'

export const GET_RATINGS_PENDING = "GET_RATINGS_PENDING"
export const GET_RATINGS_FULFILLED = "GET_RATINGS_FULFILLED"
export const GET_RATINGS_REJECTED = "GET_RATINGS_REJECTED"