export const GET_CONSULTANT_SLOT_LIST_PENDING = 'GET_CONSULTANT_SLOT_LIST_PENDING'
export const GET_CONSULTANT_SLOT_LIST_FULFILLED = 'GET_CONSULTANT_SLOT_LIST_FULFILLED'
export const GET_CONSULTANT_SLOT_LIST_REJECTED = 'GET_CONSULTANT_SLOT_LIST_REJECTED'

export const GET_RATINGS_PENDING = "GET_RATINGS_PENDING"
export const GET_RATINGS_FULFILLED = "GET_RATINGS_FULFILLED"
export const GET_RATINGS_REJECTED = "GET_RATINGS_REJECTED"

export const GET_ALL_CONSULTANTS_PENDING = "GET_ALL_CONSULTANTS_PENDING"
export const GET_ALL_CONSULTANTS_FULFILLED = "GET_ALL_CONSULTANTS_FULFILLED"
export const GET_ALL_CONSULTANTS_REJECTED = "GET_ALL_CONSULTANTS_REJECTED"

export const GET_ALL_CONSULTANT_APPOINTMENTS_PENDING = "GET_ALL_CONSULTANT_APPOINTMENTS_PENDING"
export const GET_ALL_CONSULTANT_APPOINTMENTS_FULFILLED = "GET_ALL_CONSULTANT_APPOINTMENTS_FULFILLED"
export const GET_ALL_CONSULTANT_APPOINTMENTS_REJECTED = "GET_ALL_CONSULTANT_APPOINTMENTS_REJECTED"

export const GET_SCHEDULE_TIMING_PENDING = "GET_SCHEDULE_TIMING_PENDING"
export const GET_SCHEDULE_TIMING_FULFILLED = "GET_SCHEDULE_TIMING_FULFILLED"
export const GET_SCHEDULE_TIMING_REJECTED = "GET_SCHEDULE_TIMING_REJECTED"