
export const GET_SECTORS_PENDING = "GET_SECTORS_PENDING"
export const GET_SECTORS_FULFILLED = "GET_SECTORS_FULFILLED"
export const GET_SECTORS_REJECTED = "GET_SECTORS_REJECTED"




export const GET_INDUSTRIES_PENDING = "GET_INDUSTRIES_PENDING"
export const GET_INDUSTRIES_FULFILLED = "GET_INDUSTRIES_FULFILLED"
export const GET_INDUSTRIES_REJECTED = "GET_INDUSTRIES_REJECTED"


export const GET_CONSULTANTS_PENDING = "GET_CONSULTANTS_PENDING"
export const GET_CONSULTNATS_FULFILLED = "GET_CONSULTNATS_FULFILLED"
export const GET_CONSULTNATS_REJECTED = "GET_CONSULTNATS_REJECTED"

export const GET_USER_DETAILS_PENDING = "GET_USER_DETAILS_PENDING"
export const GET_USER_DETAILS_FULFILLED = "GET_USER_DETAILS_FULFILLED"
export const GET_USER_DETAILS_REJECTED = "GET_USER_DETAILS_REJECTED"

export const LOG_OUT = "LOG_OUT"