
export const GET_SECTORS_PENDING = "GET_SECTORS_PENDING"
export const GET_SECTORS_FULFILLED = "GET_SECTORS_FULFILLED"
export const GET_SECTORS_REJECTED = "GET_SECTORS_REJECTED"




export const GET_INDUSTRIES_PENDING = "GET_INDUSTRIES_PENDING"
export const GET_INDUSTRIES_FULFILLED = "GET_INDUSTRIES_FULFILLED"
export const GET_INDUSTRIES_REJECTED = "GET_INDUSTRIES_REJECTED"


export const GET_CONSULTANTS_PENDING = "GET_CONSULTANTS_PENDING"
export const GET_CONSULTNATS_FULFILLED = "GET_CONSULTNATS_FULFILLED"
export const GET_CONSULTNATS_REJECTED = "GET_CONSULTNATS_REJECTED"

export const GET_USER_DETAILS_PENDING = "GET_USER_DETAILS_PENDING"
export const GET_USER_DETAILS_FULFILLED = "GET_USER_DETAILS_FULFILLED"
export const GET_USER_DETAILS_REJECTED = "GET_USER_DETAILS_REJECTED"

export const LOG_OUT = "LOG_OUT"


export const VERIFY_CONSULTANT_PENDING = "VERIFY_CONSULTANT_PENDING"
export const VERIFY_CONSULTANT_FULFILLED = "VERIFY_CONSULTANT_FULFILLED"
export const VERIFY_CONSULTANT_FAILED = "VERIFY_CONSULTANT_FAILED"


export const CONSULTANT_LOGIN_PENDING = "CONSULTANT_LOGIN_PENDING"
export const CONSULTANT_LOGIN_FULFILLED = "CONSULTANT_LOGIN_FULFILLED"
export const CONSULTANT_LOGIN_FAILED = "CONSULTANT_LOGIN_FAILED"

export const GET_CONSULTANT_DETAILS_PENDING = "GET_CONSULTANT_DETAILS_PENDING";
export const GET_CONSULTANT_DETAILS_FULFILLED = "GET_CONSULTANT_DETAILS_FULFILLED"
export const GET_CONSULTANT_DETAILS_FAILED = "GET_CONSULTANT_DETAILS_FAILED"