import Head from 'next/head'
import Button from '../Components/UI/Button'
import { Input } from '../Components/UI/Input'
import img from "../public/images/Ellipse 6.png"
import img2 from "../public/images/Group 22.png"
import Image from 'next/image';
export default function Home() {
  return (
    <>
      <Head>
        <title>Consultancy Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-[600px] bg-light-primary relative overflow-hidden'>
        <div className="absolute top-[-75px] left-0 ...">
          <Image src={img} alt="" />
        </div>
        <div className="absolute bottom-[-120px] left-[-10px] ...">
          <Image src={img2} alt="" />
        </div>
        <div className="container">
          hi
        </div>
      </div>
    </>
  )
}
