import Head from 'next/head'
import Button from '../Components/UI/Button'
import { Input } from '../Components/UI/Input'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-3 border px-[25px] mb-2.5">
        <h2 >Test</h2>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum dolorum pariatur alias aliquid hic aliquam vel corporis ut vero perferendis?
        </p>
      </div>
      <Button variant='outlined'>
        Book Now
      </Button>
      <Input  />
    </>
  )
}
