import Head from 'next/head'
import Enquiry from '../Components/Home/Enquiry'
import Category from '../Components/Home/Category'
import Hero from '../Components/Home/Hero'
import TopConsultant from '../Components/Home/TopConsultant'
import LatestCourse from '../Components/Home/LatestCourse'
import ClientReview from "../Components/Home/ClientReview"
import Feature from "../Components/Home/Feature"
export default function Home() {
  return (
    <>
      <Head>
        <title>Consultancy Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <TopConsultant />
      <Category />
      {/* <LatestCourse /> */}
      <Feature />
      <Enquiry />
    </>
  )
}
